### ISSUE TITLE
线上构建项目 Cannot find module 'umi-plugin-keep-alive' 

### ISSUE THREAD

**Issue by Cooper1886** [alitajs/umi-plugin-keep-alive#101]
线上构建的时候 报错 Cannot find module 'umi-plugin-keep-alive' from '/var/jenkins_home/workspace/***'
Error: Cannot find module 'umi-plugin-keep-alive' from '/var/jenkins_home/workspace/***
    at Function.resolveSync [as sync] (/var/jenkins_home/workspace/***/node_modules/@umijs/deps/compiled/resolve/index.js:1:11170)

本地项目使用没有问题，build也没有问题，线上构建的时候出问题了

**Comment by CJY0208** [comment]
需要确保 jks 任务中正常进行依赖安装
