### ISSUE TITLE
请问有没有umijs下的route+tab的demo

### ISSUE THREAD

**Issue by cd711** [alitajs/umi-plugin-keep-alive#13]
如题，
是不是不能使用umijs3的默认路由方案

**Comment by CJY0208** [comment]
写了一个，可以瞅瞅

https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy

**Comment by cd711** [comment]
> 写了一个，可以瞅瞅
> 
> https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy

thank you！
原来这么直接，我总想着在layout或者route去改造

**Comment by CJY0208** [comment]
是的，和 vue 类似的使用方式，demo 中的实现还不是特别智能化，每个 pages 都需要 KeepAlive 包裹，可以找途径自动统一处理

**Comment by henryzp** [comment]
@CJY0208 ，看了一下demo，有个疑问，就是源码里面，用的是：

```js
import { KeppAlive } from 'react-activation';
```

那我是不是可以理解成完全不用umi这个插件，直接装`react-activation`的依赖就行了？

**Comment by CJY0208** [comment]
不是的，umi 插件依然需要使用，react-activation 工作的前提是放置 AliveScope 在合适位置

当前 umi-plugin-keep-alive 主要做的事情就是放置 AliveScope

示例中 from 'react-activation' 的原因是 codesanbox 中 umi 的一些功能有影响所以这么写的，实际上使用了 umi-plugin-keep-alive 后，KeepAlive 可以直接由 umi 导出

import { KeepAlive } from 'umi'

**Comment by henryzp** [comment]
@CJY0208 ，那在umi配置中，也要导入那个插件吧？

**Comment by CJY0208** [comment]
umi3 不需要再声明 plugins: [] 了，因为会自动加载依赖中的 umi-plugin-* 或 @umijs/plugin-*

在配置中导入 plugins 反而会报重复导入的错

**Comment by henryzp** [comment]
好像是这样，之前加了，确实报这个错，thx。。。
