### ISSUE TITLE
umi的title失效

### ISSUE THREAD

**Issue by Col0ring** [alitajs/umi-plugin-keep-alive#15]
使用该插件会让umi的title无效，地址栏变成本地localhost。复现可直接新建一个umi的项目并且填写title，然后下载该插件查看效果。

**Comment by CJY0208** [comment]
v0.0.1-beta.13 fixed, thanks

**Comment by chenvd** [comment]
我在umi 3.2.14和0.0.1-beta.16还是有这个问题
