### ISSUE TITLE
有没有大佬使用这个做出了多页签！

### ISSUE THREAD

**Issue by k983551019** [alitajs/umi-plugin-keep-alive#17]
有没有大佬使用这个做出了多页签！
求求求啊

**Comment by CJY0208** [comment]
看看这个 demo https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy

**Comment by k983551019** [comment]
ni zh

> 看看这个 demo https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy

这个和主页Code的用法不一样。。 所以以demo为主？

**Comment by CJY0208** [comment]
README 只展示了基础用法，和 demo 中不冲突的

**Comment by wananle** [comment]
> 看看这个 demo https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy

复制了domo的pages两个页面和KeepAliveTabs的页面在项目中，getCachingNodes()，获取到的是一个空数组

**Comment by xueyou2000** [comment]
使用umi开发的时候，tab页内的代码改变保存后， 路由里会有2个tab内容，导致异常的问题
