### ISSUE TITLE
pro v5新项目下采用tabs-demo，用KeepAlive包含的组件出错

### ISSUE THREAD

**Issue by wananle** [alitajs/umi-plugin-keep-alive#18]
![image](https://user-images.githubusercontent.com/48664370/89510451-270ebc00-d803-11ea-9002-522733637956.png)

![image](https://user-images.githubusercontent.com/48664370/89510670-705f0b80-d803-11ea-9244-9d4ed691de2e.png)

**Comment by CJY0208** [comment]
可以发一个完整 demo 吗，看不出问题在哪儿

**Comment by wananle** [comment]
> 可以发一个完整 demo 吗，看不出问题在哪儿

https://github.com/wananle/demo，这个demo是在v5的基础上采用umi-keep-alive-tabs-demo，然后就出错。

**Comment by erlei22** [comment]
同遇到这个报错，请问有解决方案吗

**Comment by fh345392977** [comment]
[keep-alive-error](https://github.com/fh345392977/keep-alive.git)

这是复现库，下面说说我遇到的奇怪的地方。

仓库总共三个分支，keep-alive分支是只安装插件，但未使用。

keep-alive-error是最小使用情景，只给了一个页面keep-alive。

master分支虽然也只有一个页面使用，但在某个hook里用到了`useAliveController`。

直接拉取`keep-alive-error`分支，`yarn && yarn start` ，报错。
直接拉取`keep-alive`，`yarn && yarn start`，然后切换分支到master，正常。关闭后执行`rm -rf src/.umi`，再次`yarn start`启动，报错。
直接拉取`master`，`yarn && yarn start`，报错。

猜测是`umi g tmp`产生的问题，可能和路由有关，也可能和`tree-shaking`有关。

很遗憾没找到解决办法。

**Comment by CJY0208** [comment]
OK，本周末尝试定位

**Comment by chj-damon** [comment]
我也遇到一样的报错。

**Comment by CJY0208** [comment]
目前 debugger 的进度为，原因可能由 umi-ui 插入了特定代码片段所致，修正方式有 2

1. 关闭 umi-ui 功能
2. 在 KeepAlive 包裹外增加一层 Fragment，参考如下代码
```jsx
// src/pages/home.js
import { KeepAlive } from 'umi'

function HomePage() {
  ...
}

export default () => (
  <>
    <KeepAlive>
      <HomePage />
    </KeepAlive>
  </>
)
```

**Comment by CJY0208** [comment]
umi-ui 放了两个额外的 GUmiUIFlag 标签进来，导致 KeepAlive 的 children 变成了一个数组，cloneElement 报错了
https://stackoverflow.com/questions/38011702/how-to-clone-multiple-children-with-react-cloneelement
https://github.com/CJY0208/react-activation/blob/c29358da1fb78f56bd2acd190f5642af46c9bd79/src/core/Keeper.js#L139-L141

**Comment by CJY0208** [comment]
尝试升级到 0.0.1-beta.20 版本以修正 umi-ui 引起的问题

**Comment by CJY0208** [comment]
应该修复了，先关闭，有问题再开
