### ISSUE TITLE
既然都有keep alive了，不如搞一个多umi + procomponents 多tab页面案例的demo

### ISSUE THREAD

**Issue by ouzhou** [alitajs/umi-plugin-keep-alive#24]
既然都有keep alive了，不如搞一个多umi + procomponents 多tab页面案例的demo

**Comment by CJY0208** [comment]
目前 keep-alive 工具并未得到 umi 官方认可，与其实现原理，不太推荐 tabs 等重度使用场景，易于产生性能问题

所以当前库也只是提供功能，仅提供轻型 demo，不提供重型 demo

目前存在一个多 tabs 示例，可参考此处：https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy
