### ISSUE TITLE
源码里 增加fixCustomizedRuntime的意图是什么

### ISSUE THREAD

**Issue by hoozi** [alitajs/umi-plugin-keep-alive#27]
注释不是很理解，rootContainer第一个参数container不是表示上一个contianer吗？container算是children吧。为什么会丢失用户配置的rootContainer

**Comment by CJY0208** [comment]
问题背景 https://github.com/alitajs/umi-plugin-keep-alive/issues/16
对应的 PR：https://github.com/umijs/umi/pull/5055

目前是 PR 不通过，担心有风险，所以 fixCustomizedRuntime 为修正方案
