### ISSUE TITLE
对 Context 的破坏性影响，需手动修复？结合PageContainer组件不能自动展示title以及breadcrumb信息？

### ISSUE THREAD

**Issue by wangJacker** [alitajs/umi-plugin-keep-alive#30]
底层实现基于react-activation实现：https://github.com/CJY0208/react-activation/blob/master/README_CN.md ，请问这个对 Context 的破坏性影响修复了吗？如果项目使用PageContainer有什么修复方法么？ 尝试修改过源码，好像并没有起到作用 可能没修改对，麻烦了

**Comment by CJY0208** [comment]
对 Context 的破坏性影响没有办法无感知修复，需求根据说明示例手动修复，查看了 antd-pro 相关源码，大概如此

```jsx
import { ConfigProvider } from 'antd'
import { RouteContext } from '@ant-design/pro-layout'
import { fixContext  } from 'react-activation'
// or import { fixContext } from 'umi''

// PageContainer 依赖了 RouteContext、ConfigProvider.ConfigContext
fixContext(RouteContext)
fixContext(ConfigProvider.ConfigContext)
```

**Comment by wangJacker** [comment]
好的谢谢了非常感谢 ！还有一种方式是将PageContainer 放在AliveScope的外层能避免这个问题 。`<PageContainer><AliveScope></AliveScope></PageContainer> `

**Comment by CJY0208** [comment]
第二种方式不推荐，AliveScope 被卸载后，缓存将失效

**Comment by wangJacker** [comment]
的确 放在外层后页面有太多的局限性  不能自定义 不能放置按钮什么的
