### ISSUE TITLE
antd pro v4 报错 Error: Rendered more hooks than during the previous render

### ISSUE THREAD

**Issue by q350241636** [alitajs/umi-plugin-keep-alive#34]
export default () => (
    <KeepAlive name="/system/user" saveScrollPosition="screen">
      <TableList />
    </KeepAlive>
);

刷新页面报错

**Comment by CJY0208** [comment]
降低版本到 0.0.1-beta.21 试试会不会有问题

**Comment by q350241636** [comment]
好用了 感谢！
方便说下2.2修改了什么地方 导致的这个问题呢

**Comment by CJY0208** [comment]
增加了一个自动修复上下文断层的方法，没想到引发了额外的问题

你的问题场景可以做成在线 demo 嘛？对我们研究价值会比较大

**Comment by q350241636** [comment]
> 增加了一个自动修复上下文断层的方法，没想到引发了额外的问题
> 
> 你的问题场景可以做成在线 demo 嘛？对我们研究价值会比较大

好的 我研究一下 传上去

**Comment by CJY0208** [comment]
试试 0.0.1-beta.25

**Comment by 97thjingba** [comment]
我遇到了相同的问题.. . 刷新页面. 出现同样的错误

**Comment by CJY0208** [comment]
@97thjingba 如果可以的话最好啦，感谢
