### ISSUE TITLE
首次加载刷新页面报错

### ISSUE THREAD

**Issue by huanlirui** [alitajs/umi-plugin-keep-alive#35]
刷新页面：
Warning: React has detected a change in the order of Hooks called by HooksConsumerBridge. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hook

 Rendered more hooks than during the previous render。

如果取消掉 <KeepAlive> 在页面加完成后。再加上 <KeepAlive>嵌套。代码热更新时就不会报错。
刷新页面又会出错。

**Comment by CJY0208** [comment]
试试 0.0.1-beta.25
