### ISSUE TITLE
antd pro v4中，如果用keepAlive包裹了antd的Input组件，就会报错

### ISSUE THREAD

**Issue by cnyhazz** [alitajs/umi-plugin-keep-alive#36]
![image](https://user-images.githubusercontent.com/15262865/110076782-066e0b00-7dc0-11eb-8346-0cf45bdd431a.png)
![image](https://user-images.githubusercontent.com/15262865/110076808-0ff77300-7dc0-11eb-8eeb-dd5251970d01.png)

**Comment by mathcw** [comment]
同样遇到这个问题 @CJY0208

**Comment by CJY0208** [comment]
@mathcw 插件是啥版本呀，是 0.0.1-beta.23 吗

**Comment by mathcw** [comment]
> @mathcw 插件是啥版本呀，是 0.0.1-beta.23 吗

umi-plugin-keep-alive :0.0.1-beta.23
antd:4.14.0

**Comment by mathcw** [comment]
umi-plugin-keep-alive :0.0.1-beta.23
antd:4.14.0
react:17.0.1
@CJY0208

**Comment by mathcw** [comment]
@CJY0208 [最小复现](https://codesandbox.io/s/umi-keep-alive-tabs-demo-forked-dgixz)

**Comment by CJY0208** [comment]
尝试升级到 v0.0.1-beta.24 进行修复
