### ISSUE TITLE
ant-design pro5 页面路由切换， effect函数仍然会执行

### ISSUE THREAD

**Issue by liuxiansheng2018** [alitajs/umi-plugin-keep-alive#38]
复现 内容 https://codesandbox.io/s/epic-jackson-tbr6i?file=/src/App.js

**Comment by CJY0208** [comment]
KeepAlive 只能缓存它内部的组件，像这样
![image](https://user-images.githubusercontent.com/18415774/113104699-6d51d900-9233-11eb-92a5-1be483451640.png)
