### ISSUE TITLE
直接报错，不能使用

### ISSUE THREAD

**Issue by kkerwin** [alitajs/umi-plugin-keep-alive#39]
版本：
![164642](https://user-images.githubusercontent.com/7856025/113268475-fdfae880-9309-11eb-90f0-454ebe6603b9.png)

项目：
https://codesandbox.io/s/modest-snow-j1d9q

**Comment by CJY0208** [comment]
codesandbox 时可能需要换成从 react-activation 导出 KeepAlive

![image](https://user-images.githubusercontent.com/18415774/113368853-4fe75100-9392-11eb-85e8-dea24489ee91.png)

**Comment by kkerwin** [comment]
好的，谢谢！
不是codesandbox 的问题，我本地项目也是这样的。用 react-activation 导出 KeepAlive 就没有问题
