### ISSUE TITLE
如何引入的问题

### ISSUE THREAD

**Issue by theDoinb** [alitajs/umi-plugin-keep-alive#40]
umi版本：2.10.4

直接 import { KeepAlive } from 'umi'，发现取不到 KeepAlice，

所以看了看 umi2 的插件文档，
加入了以下配置：
 plugins: [
    [
      'umi-plugin-keep-alive',{}
    ],
    [
      'umi-plugin-react',
      {
        ..........
      }
]
又抛出以下错误：

⬤  debug     [add] config\config.js___jb_tmp___
[ ]  pending   Since Config base Changed, try to restart server...
F:\wingo\netmas-web-react-v2\node_modules\umi-build-dev\lib\Service.js:182
        throw new Error(e);
        ^

Error: Error: Plugin F:/wingo/netmas-web-react-v2/node_modules/umi-plugin-keep-alive/lib/index.js execute failed

Cannot find module '@@/history'
Require stack:
- F:\wingo\netmas-web-react-v2\node_modules\umi\lib\router.js
- F:\wingo\netmas-web-react-v2\node_modules\umi\lib\index.js
- F:\wingo\netmas-web-react-v2\node_modules\umi\index.js
- F:\wingo\netmas-web-react-v2\node_modules\umi-plugin-keep-alive\lib\index.js
- F:\wingo\netmas-web-react-v2\node_modules\umi-build-dev\lib\getPlugins.js
- F:\wingo\netmas-web-react-v2\node_modules\umi-build-dev\lib\Service.js
- F:\wingo\netmas-web-react-v2\node_modules\umi\lib\scripts\realDev.js
    at Service.resolvePlugins (F:\wingo\netmas-web-react-v2\node_modules\umi-build-dev\lib\Service.js:182:15)
    at new Service (F:\wingo\netmas-web-react-v2\node_modules\umi-build-dev\lib\Service.js:156:25)
    at Object.<anonymous> (F:\wingo\netmas-web-react-v2\node_modules\umi\lib\scripts\realDev.js:49:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by CJY0208** [comment]
直接从 react-activation 取试试

**Comment by theDoinb** [comment]
试过了，直接用 react-activation 会出现和 [#52](https://github.com/CJY0208/react-activation/issues/52#issue-655760084) 相同的情况

**Comment by CJY0208** [comment]
umi 插件可以不移除，只是 KeepAlive 改成从 react-activation 去取而不是 umi

**Comment by theDoinb** [comment]
还是不行，构造器的值 和 state 的值全初始化了，input（非受控组件） 里的值，却保留了，

umi3 好像才会 识别 umi- 头自动引入，估摸着 Umi2 这样相当于直接用了  react-activation

**Comment by CJY0208** [comment]
是的，umi2 里依然需要自己引入 react-activation，而且现在可能已经不支持 2 了= =

**Comment by theDoinb** [comment]
升级到了umi3 了，从umi引入了，但是还是有问题，进去应该是缓存到了，

但是页面点击查询， props 和 state 的 change 后，页面渲染失效了，

打印了下数据，确认返回了页面，但是没有进行渲染，

应该可能是缓存导致的，返回了之前的 children

**Comment by theDoinb** [comment]
把 keepAlive 提到 basicLayout，裹住children 貌似正常了

```
         {
                  pathname==='/networkDevice/device' ?
                    <KeepAlive>
                      <div style={{margin: hideSubMenu?0:'16px 24px'}}>
                        {children}
                      </div>
                    </KeepAlive> :
                    <div style={{margin: hideSubMenu?0:'16px 24px'}}>
                      {children}
                    </div>
                }
```

**Comment by yuanguandong** [comment]
> 是的，umi2 里依然需要自己引入 react-activation，而且现在可能已经不支持 2 了= =

如果一定要在umi2里使用，有什么方式吗？

**Comment by CJY0208** [comment]
可以试试直接使用 react-activation ，不使用当前仓库的包，AliveScope 就不用放了，直接用 KeepAlive
