### ISSUE TITLE
可以在组件卸载时再缓存吗

### ISSUE THREAD

**Issue by Attiley** [alitajs/umi-plugin-keep-alive#41]
我想使用react virtualized的infinite loader在向下滚动时发送ajax请求获取数据实现无限加载，然后在页面切换时保存组件状态和scrollTop。
但是在使用Keepalive时发现向下滚动不能加载数据了，只有useEffect第一次加载的数据。
能不能在history.push的时候再缓存呢？

**Comment by CJY0208** [comment]
目前是在触发了 componentWillUnmount 周期进行缓存的，这个周期是不是早了

**Comment by Attiley** [comment]
可能是react virtualized自己的问题吧，😵。
我如果不用infinite loader分段获取数据，直接一次获取所有数据就不会出现这个问题了，使用十分良好。
十分感谢
