### ISSUE TITLE
和umi-plugin-access不兼容

### ISSUE THREAD

**Issue by Attiley** [alitajs/umi-plugin-keep-alive#42]
使用的框架是ant design pro v5最新版本
package.json:

```
"dependencies": {
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^6.15.3",
    "@ant-design/pro-table": "^2.30.8",
    "@umijs/openapi": "^1.1.14",
    "@umijs/plugin-openapi": "^1.2.0",
    "@umijs/route-utils": "^1.0.36",
    "antd": "^4.14.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.4.11",
    "umi-request": "^1.0.8",
    "umi-plugin-keep-alive": "0.0.1-beta.26"
  },
```
access.ts
```
export default function access() {
  return {
    canAdmin: false
  };
}

```
routes.ts
```
  {
    path: '/welcome',
    name: 'welcome',
    component: './Welcome',
    access:'canAdmin'
  },
```
去除umi-plugin-keep-alive依赖时，access使用正常，菜单栏没有welcome，但是装上keepalive以后access失效

**Comment by Attiley** [comment]
可能跟rootContainer有关？

**Comment by Attiley** [comment]
能帮助解决一下吗，不然动态菜单好像没法做😥

**Comment by 510846** [comment]
我也碰到这个问题了，亟待解决 ~ 在线等 ~

**Comment by penciltian** [comment]
同样遇到这个问题，然后用回了react-activation插件，react-activation没有权限这个问题。
但是发现了一个新的问题，表格属性中使用ellipsis：true,会导致缓存出来的表格数据变成三个点（...）。
umi-plugin-keep-alive和react-activation都有这个问题，我才应该是react-activation带来的问题。
![image](https://user-images.githubusercontent.com/19288219/119307238-f7e80f00-bc9d-11eb-8318-12ce74e168dd.png)
![image](https://user-images.githubusercontent.com/19288219/119307306-13ebb080-bc9e-11eb-84a3-48d5c3c57581.png)
我的解决方法是：使用render，重新定义超出隐藏的代码，缓存后重新渲染不会变成省略号。ellipsis: true,不能省略，不然那表格会变形。
![image](https://user-images.githubusercontent.com/19288219/119308350-827d3e00-bc9f-11eb-81ab-25eb19170c27.png)
![image](https://user-images.githubusercontent.com/19288219/119308411-97f26800-bc9f-11eb-84cd-49765ec203bf.png)

**Comment by Attiley** [comment]
> 同样遇到这个问题，然后用回了react-activation插件，react-activation没有权限这个问题。
> 但是发现了一个新的问题，表格属性中使用ellipsis：true,会导致缓存出来的表格数据变成三个点（...）。
> umi-plugin-keep-alive和react-activation都有这个问题，我才应该是react-activation带来的问题。
> ![image](https://user-images.githubusercontent.com/19288219/119307238-f7e80f00-bc9d-11eb-8318-12ce74e168dd.png)
> ![image](https://user-images.githubusercontent.com/19288219/119307306-13ebb080-bc9e-11eb-84a3-48d5c3c57581.png)
> 我的解决方法是：使用render，重新定义超出隐藏的代码，缓存后重新渲染不会变成省略号。ellipsis: true,不能省略，不然那表格会变形。
> ![image](https://user-images.githubusercontent.com/19288219/119308350-827d3e00-bc9f-11eb-81ab-25eb19170c27.png)
> ![image](https://user-images.githubusercontent.com/19288219/119308411-97f26800-bc9f-11eb-84cd-49765ec203bf.png)

但是React-activation怎么包裹入口文件呢，umi好像没有入口文件😓，app.tsx也都是配置文件

**Comment by Adskoy** [comment]
Wow, this is still open

Regarding the issue with access: after a quick exploration I figured, that it is caused by the order of AliveScope wrapper:

> 注入顺序可以通过 addRuntimePlugin 的 stage 属性进行调整，目前是将 keep-alive 插件的优先级调至最低了，没想到会覆盖用户自定义的 app rootContainer
> 
> https://github.com/alitajs/umi-plugin-keep-alive/blob/ea1d8f2225b4a9d6ab15add0414a6aa836a46d2c/src/index.js#L6-L9
> 
> 目前只能快速响应，不过还没时间处理，如果可以的话，可以在找到方案后提个 PR~

Changing plugin registration code to this
`api.addRuntimePlugin(() => '@@/plugin-keep-alive/runtime');`
fixes the issue.

Dunno if it's woth pr

**Comment by AndroidMilk** [comment]
什么时候修复一下

**Comment by CJY0208** [comment]
@AndroidMilk react 是否是 17+ 版本？

**Comment by AndroidMilk** [comment]
> @AndroidMilk react 是否是 17+ 版本？

是的

**Comment by CJY0208** [comment]
@AndroidMilk React 17 的话可以尝试用以下方式看看能否修复 access 的问题

```jsx
import { autoFixContext } from 'react-activation'

autoFixContext(
  [require('react/jsx-runtime'), 'jsx', 'jsxs', 'jsxDEV'],
  [require('react/jsx-dev-runtime'), 'jsx', 'jsxs', 'jsxDEV']
)
```

**Comment by AndroidMilk** [comment]
> @AndroidMilk React 17 的话可以尝试用以下方式看看能否修复 access 的问题
> 
> ```jsx
> import { autoFixContext } from 'react-activation'
> 
> autoFixContext(
>   [require('react/jsx-runtime'), 'jsx', 'jsxs', 'jsxDEV'],
>   [require('react/jsx-dev-runtime'), 'jsx', 'jsxs', 'jsxDEV']
> )
> ```

好的

**Comment by AndroidMilk** [comment]
> ```js
> import { autoFixContext } from 'react-activation'
> 
> autoFixContext(
>   [require('react/jsx-runtime'), 'jsx', 'jsxs', 'jsxDEV'],
>   [require('react/jsx-dev-runtime'), 'jsx', 'jsxs', 'jsxDEV']
> )
> ```

请教下这个加在哪个地方

**Comment by CJY0208** [comment]
应用入口处就 OK 了

**Comment by CJY0208** [comment]
查明原因是 access plugin 会 clone rootContainer 的根节点，并传入 routes 属性

keep-alive plugin 的 rootContainer 根节点为 AliveScope，破坏了这一性质

 0.0.1-beta.30 版本修复了此问题，感谢 @JS-an

**Comment by ZacksTsang** [comment]
什么时候可以下载？

**Comment by CJY0208** [comment]
@ZacksTsang 发布 CI 挂了，稍等，我重发一下

**Comment by CJY0208** [comment]
@ZacksTsang 发上去了，可以试试

**Comment by ZacksTsang** [comment]
@CJY0208  可以了，谢谢

**Comment by gaoyayun** [comment]
同样的问题，权限不生效，升级一下就可以了，感谢感谢
