### ISSUE TITLE
Can't adapt to the new feature mfsu of umi 3.5

### ISSUE THREAD

**Issue by gwsbhqt** [alitajs/umi-plugin-keep-alive#49]
After upgrading and troubleshooting multiple projects, it can be determined that KeepAlive has a serious conflict with mfsu.
I hope the author can solve this problem to be compatible with the new features of umi. thanks a lot.
![image](https://user-images.githubusercontent.com/16471930/123915003-9b6dc300-d9b2-11eb-82fb-33de9559a736.png)

**Comment by CJY0208** [comment]
有可复现的项目地址吗？还是任意 umi 项目接入此插件后，开启 mfsu 都会报错呢

**Comment by FireTable** [comment]
+1，应该是umijs官网提醒的react重复的问题

**Comment by xiaohuoni** [comment]
umi-plugin-keep-alive@0.0.1-beta.29

**Comment by gwsbhqt** [comment]
@xiaohuoni nice job, it work for me.
