### ISSUE TITLE
在umi中使用不生效

### ISSUE THREAD

**Issue by LiuL0703** [alitajs/umi-plugin-keep-alive#5]
```js
"react": "16.12.0",
"umi": "2.10.6",
"umi-plugin-keep-alive": "^0.0.1-beta.6",
```

**Comment by LiuL0703** [comment]
<img src="https://user-images.githubusercontent.com/13818610/71304520-f6f4e300-2402-11ea-8e80-8a3020e71d3b.png" width="50%" height="50%" />
并未缓存内容 @CJY0208

**Comment by CJY0208** [comment]
可以在 umi@3,x 中尝试 umi-plugin-keep-alive@0.0.1-beta.9 版本试试

**Comment by rudyzou** [comment]
删除缓存好像没效果诶

**Comment by phoebeCodeSpace** [comment]
> 删除缓存好像没效果诶，dropscope

我也没效果。😹

**Comment by CJY0208** [comment]
@phoebeCodeSpace @rudyzou 
抱歉现在才注意到这条留言，请问你们是在 KeepAlive 激活期间使用 drop 相关动作吗？

react-activation 忽略了这个行为，因为这被认为不属于 “drop” 动作而是 "refresh"

此场景下需要使用 refresh、refreshScope 而不是 drop

**Comment by phoebeCodeSpace** [comment]
> @phoebeCodeSpace @rudyzou
> 抱歉现在才注意到这条留言，请问你们是在 KeepAlive 激活期间使用 drop 相关动作吗？
> 
> react-activation 忽略了这个行为，因为这被认为不属于 “drop” 动作而是 "refresh"
> 
> 此场景下需要使用 refresh、refreshScope 而不是 drop
> 
> 如果是多 tabs 标签，需要是关闭后回到上一个路由或者标签的需求场景，那需要在进行路由切换，触发 KeepAlive 的卸载后再调用 drop 函数
> 
> 原因是 react-activation 被设计为与路由系统无关，不会主动猜测路由行为且进行路由引导

早上研究了下确实是这个问题，在当前路由下关闭tab，drop无效。
refresh、refreshScope解决方案可行。感谢~

**Comment by CJY0208** [comment]
试试 0.0.1-beta.25，drop 更智能了一些
