### ISSUE TITLE
生命周期钩子函数无效

### ISSUE THREAD

**Issue by wmmmy** [alitajs/umi-plugin-keep-alive#51]
useActivate、 useUnactivate、withActivation、withAliveScope、useAliveController使用都无效

**Comment by CJY0208** [comment]
给个复现 demo 吧，感谢

**Comment by wmmmy** [comment]
ant-design-pro 4.2.0,
umi: "^3.2.0",
umi-plugin-keep-alive: "^0.0.1-beta.29"



keepalive功能可以正常使用，但是useActivate、 useUnactivate里面的log没有打印。
换了class写法也是一样

**Comment by wmmmy** [comment]
![af45926dbbebb5d0d250f47486f994f0](https://user-images.githubusercontent.com/62919209/124215090-f70c8d80-db25-11eb-8adf-b967838dbff5.png)
![3f32ad84fa8c45393fe06684d6920a0a](https://user-images.githubusercontent.com/62919209/124215113-0095f580-db26-11eb-8c41-eb1d8cb435d7.png)

**Comment by CJY0208** [comment]
使用方法的原因

```jsx

const Test =() => {
  
  useActivate(...)  

  return (
    <KeepAlive>...</KeepAlive>
  )
}

export default Test
```

调整为

```jsx

const Test =() => {
  
  useActivate(...)  

  return (
    ...
  )
}

export default (props) => (
  <KeepAlive>
    <Test {...props} />
  </KeepAlive>
)
```

**Comment by CJY0208** [comment]
KeepAlive 内部的组件才能响应缓存生命周期
