### ISSUE TITLE
在umi3如何统一配置，而不是在每个页面手动加入KeepAlive标签

### ISSUE THREAD

**Issue by zwj7181** [alitajs/umi-plugin-keep-alive#53]
现在看来很多示例都是在pages页面加KeepAlive
```
export default () => (
  <KeepAlive name="/home" saveScrollPosition="screen">
    <Home />
  </KeepAlive>
)
```

如何在layout配置KeepAlive呢？类似react-keep-alive-pro
```
<Route
      exact
      key={path}
      path={path}
      render={(props) => {
        return (
          <KeepAlive name={`${path}.name`}>
            <div className="keep-alive-wrapper">
              <ResizeContainer>
                {(containerProps) => {
                  return (
                    <Suspense fallback={<CustomSpin />}>
                      <ErrorBoundary>
                        <Component {...this.props} />
                      </ErrorBoundary>
                    </Suspense>
                  );
                }}
              </ResizeContainer>
            </div>
          </KeepAlive>
        );
      }}
  />
```

**Comment by CJY0208** [comment]
和上述用法类似，不过在 react-activation 中关键生效的参数是 id
参考此处：https://github.com/CJY0208/react-activation#multiple-cache

**Comment by 1195002442** [comment]
根据大佬提供的思路，弄了一个小demo的多页签，在统一入口配置了一下，需要的可以看看

**Comment by 1195002442** [comment]
> 现在看来很多示例都是在pages页面加KeepAlive
> 
> ```
> export default () => (
>   <KeepAlive name="/home" saveScrollPosition="screen">
>     <Home />
>   </KeepAlive>
> )
> ```
> 
> 如何在layout配置KeepAlive呢？类似react-keep-alive-pro
> 
> ```
> <Route
>       exact
>       key={path}
>       path={path}
>       render={(props) => {
>         return (
>           <KeepAlive name={`${path}.name`}>
>             <div className="keep-alive-wrapper">
>               <ResizeContainer>
>                 {(containerProps) => {
>                   return (
>                     <Suspense fallback={<CustomSpin />}>
>                       <ErrorBoundary>
>                         <Component {...this.props} />
>                       </ErrorBoundary>
>                     </Suspense>
>                   );
>                 }}
>               </ResizeContainer>
>             </div>
>           </KeepAlive>
>         );
>       }}
>   />
> ```

根据大佬提供的思路和基础上，在同一入口处进行了配置，算是实现了这个需求
