### ISSUE TITLE
包裹组件后直接报错了

### ISSUE THREAD

**Issue by XinYueXiao** [alitajs/umi-plugin-keep-alive#54]
![image](https://user-images.githubusercontent.com/31272499/133415080-c6a6be3c-fe86-4004-9b12-0924929181a2.png)
![image](https://user-images.githubusercontent.com/31272499/133415137-9496e3e1-5ffe-41aa-a7e0-5125dd0acff7.png)

**Comment by CJY0208** [comment]
export default () => (<>...</>)
