### ISSUE TITLE
Layout内使用PageContainer 会导致title栏的背景缺少

### ISSUE THREAD

**Issue by bailuren** [alitajs/umi-plugin-keep-alive#58]
![lQLPDhsULvtWzv9izQK0sFcTIWNaP8yAAfG97BeAuQA_692_98](https://user-images.githubusercontent.com/28099704/150629255-e2860260-bb00-4c06-9d4f-024426e071cc.png)

正常如下 

![lQLPDhsULw8CNKlWzQJtsNJxhBlouNf5AfG-C9tAeAA_621_86](https://user-images.githubusercontent.com/28099704/150629257-632b7856-bc33-416b-8fa8-4cbeb2a6e1a8.png)

**Comment by CJY0208** [comment]
KeepAlive 会新增两个 dom 节点外层 `.ka-wrapper` 和 `.ka-content`，你的场景中大概是这两个外层影响了样式，需要根据这两个 `className`、结合你的场景进行样式修正

实现原因，这两个外层暂时无法撤除
