### ISSUE TITLE
配合dva插件一起使用的时候，dispatch更新state时，页面没有更新，切换才能更新视图

### ISSUE THREAD

**Issue by ZmSama** [alitajs/umi-plugin-keep-alive#60]

**Comment by CJY0208** [comment]
给个 demo 吧，没用过 dva

**Comment by ZmSama** [comment]
我把这个手里的demo上传到码云去，然后给你看看，我已经搭建好环境了，你直接测试即可，就在那个客户的界面，在连接函数那里，你注释KeepAlive测试一下可以更新视图，放开注释就不行了
这是仓库地址：
https://gitee.com/liao_zi_mo/demo-keep-alive-test.git
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alitajs/umi-plugin-keep-alive"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 上午9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alitajs/umi-plugin-keep-alive] 配合dva插件一起使用的时候，dispatch更新state时，页面没有更新，切换才能更新视图 (Issue #60)





 
给个 demo 吧，没用过 dva
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CMG-CEO** [comment]
缓存的时候要缓存组件，而models里面的数据不能缓存，不然就出现，实际执行代码，而页面没有更新。
所以要对connect这里改造一下，缓存一个组件，这个组件再connectmodels
```
//connect导出一个组件，里面的props是自己获取的，不会被缓存住

const UserInfo = connect(({ __login,}) => ({
  __login,
}))(UserInfoIndex);

class UserInfoKeep extends PureComponent {
  constructor(props) {
    super(props);
    this.state = {};
  }
  render() {
    return (
      <KeepAlive>
      // UserInfo被缓存了
        <UserInfo />
      </KeepAlive>
    );
  }
}
// 最终导出被缓存的组件
export default connect()(UserInfoKeep);

```

**Comment by CJY0208** [comment]
0.0.1-beta.31 修复了这个问题，是 react-activation 的一个历史遗留问题导致的，之前一直没被定位到，昨天修复了，今天 umi-plugin-keep-alive 也修复了此问题

@CMG-CEO 新版本可能不再需要额外的写法来处理，可以试试普通 connect 写法~ 感谢
