### ISSUE TITLE
umi@2想实现点击跳转再返回来记住前一个页面不刷新

### ISSUE THREAD

**Issue by 420407904** [alitajs/umi-plugin-keep-alive#68]
很抱歉打扰到你，
我尝试调试和查阅了很久，看了@alitajs/tabs-layout
我现在想的是用umi-plugin-keep-alive同时把我的umi升到@3来尝试下，这个稳定么，或者大佬现在有更好的方案了吗

**Comment by CJY0208** [comment]
umi2可以直接使用 react-activation 试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月28日(周二) 下午5:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [alitajs/umi-plugin-keep-alive] ***@***.***想实现点击跳转再返回来记住前一个页面不刷新 (Issue #68)




 
很抱歉打扰到你，
 ***@***.***/tabs-layout
 ***@***.***来尝试下，这个稳定么，或者大佬现在有更好的方案了吗

**Comment by shenjunru** [comment]
欢迎试用 [react-fiber-keep-alive](https://www.npmjs.com/package/react-fiber-keep-alive)，一个基于 react fiber 的 keep-alive 实现
