### ISSUE TITLE
umi4 使用keepAlive报错

### ISSUE THREAD

**Issue by HurriedOn** [alitajs/umi-plugin-keep-alive#75]
umi-plugin-keep-alive版本: 0.0.1-beta.34
<img width="788" alt="image" src="https://user-images.githubusercontent.com/26838083/186836663-f2d7a496-1819-4bbf-8500-79f4f2712890.png">

**Comment by Cool-Star** [comment]
umi4中的插件要手动配置引入，不会像umi3自动引入的。

**Comment by HurriedOn** [comment]
> umi4中的插件要手动配置引入，不会像umi3自动引入的。

谢谢，已解决。配置额外的 Umi 插件
```base
plugins: ['umi-plugin-keep-alive']
```

**Comment by CJY0208** [comment]
@Cool-Star thanks
