### ISSUE TITLE
@umijs/max 4.0 useMode, TypeError: Cannot read properties of null (reading 'dispatcher')

### ISSUE THREAD

**Issue by ZhengXinquan** [alitajs/umi-plugin-keep-alive#78]
[codesandbox 代码重现 ](https://codesandbox.io/p/github/ZhengXinquan/test-umi-keepalive/csb-fpesid/draft/jovial-gwen?file=%2Fsrc%2Fpages%2FHome%2Findex.tsx&workspace=%257B%2522activeFileId%2522%253A%2522cl7kap642000floit010r1hu6%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8000%252C%2522key%2522%253A%2522cl7kaqbwy00bi356h5hmzzy7v%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fhome%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl7kaq6pe006w356hj8tj8j9y%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)
## 描述：
`"@umijs/max": "^4.0.17"` 使用 `useMode` 报错： `TypeError: Cannot read properties of null (reading 'dispatcher')`  或 `TypeError: _useContext is null`
## 操作：
$ mkdir myapp && cd myapp
$ yarn create umi
✔ Pick Umi App Template › Ant Design Pro
✔ Pick Npm Client › yarn
✔ Pick Npm Registry › taobao
yarn add umi-plugin-keep-alive
.umirc.ts 添加插件 plugins: ['umi-plugin-keep-alive']
修改src/pages/home/index.ts
```
import Guide from '@/components/Guide';
import { trim } from '@/utils/format';
import { PageContainer } from '@ant-design/pro-components';
import { useModel, KeepAlive } from '@umijs/max';
import { useState } from 'react';
import styles from './index.less';

const Counter: React.FC = () => {
  const [count, setCount] = useState(0);
  const { name } = useModel('global');
  return (
    <div>
      <h1>useModel.global.name : {name}</h1>
      <p>count: {count}</p>
      <button onClick={() => setCount((count) => count + 1)}>add</button>
    </div>
  );
};

const HomePage: React.FC = () => {
  const { name } = useModel('global');
  return (
    <PageContainer ghost>
      <KeepAlive>
        <Counter />
      </KeepAlive>
      <div className={styles.container}>
        <Guide name={trim(name)} />
      </div>
    </PageContainer>
  );
};

export default HomePage;

```
## 重现：
[codesandbox 代码重现 ](https://codesandbox.io/p/github/ZhengXinquan/test-umi-keepalive/csb-fpesid/draft/jovial-gwen?file=%2Fsrc%2Fpages%2FHome%2Findex.tsx&workspace=%257B%2522activeFileId%2522%253A%2522cl7kap642000floit010r1hu6%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8000%252C%2522key%2522%253A%2522cl7kaqbwy00bi356h5hmzzy7v%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fhome%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl7kaq6pe006w356hj8tj8j9y%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

_Originally posted by @ZhengXinquan in https://github.com/alitajs/umi-plugin-keep-alive/issues/76#issuecomment-1235310615_

**Comment by CJY0208** [comment]
在 src 中增加以下代码试试

```jsx
import { autoFixContext } from 'react-activation';
import jsxRuntime from 'react/jsx-runtime'
import jsxDevRuntime from 'react/jsx-dev-runtime'
 
autoFixContext(
  [jsxRuntime, 'jsx', 'jsxs', 'jsxDEV'],
  [jsxDevRuntime, 'jsx', 'jsxs', 'jsxDEV']
)
```

**Comment by ZhengXinquan** [comment]
> 在 src 中增加以下代码试试
> 
> ```js
> import { autoFixContext } from 'react-activation';
> import jsxRuntime from 'react/jsx-runtime'
> import jsxDevRuntime from 'react/jsx-dev-runtime'
>  
> autoFixContext(
>   [jsxRuntime, 'jsx', 'jsxs', 'jsxDEV'],
>   [jsxDevRuntime, 'jsx', 'jsxs', 'jsxDEV']
> )
> ```

测试有效，谢谢🙏

**Comment by ycttp** [comment]
> > 在 src 中增加以下代码试试
> > ```js
> > import { autoFixContext } from 'react-activation';
> > import jsxRuntime from 'react/jsx-runtime'
> > import jsxDevRuntime from 'react/jsx-dev-runtime'
> >  
> > autoFixContext(
> >   [jsxRuntime, 'jsx', 'jsxs', 'jsxDEV'],
> >   [jsxDevRuntime, 'jsx', 'jsxs', 'jsxDEV']
> > )
> > ```
> 
> 测试有效，谢谢🙏
