### ISSUE TITLE
umi4+ant-design-pro6，使用的是beta34版本，会出现自动给Table的表头增加visibility：hidden属性

### ISSUE THREAD

**Issue by zhaoran12138** [alitajs/umi-plugin-keep-alive#81]
umi4+ant-design-pro6，使用的是beta34版本，会出现自动给Table的表头增加visibility：hidden属性，使用样式覆盖掉会导致有些固定列的表格表头样式错乱，不使用KeepAlive后表头不会隐藏，之前的功能正常。
请问是否是因为没有识别到这里，没有增加_nk属性导致的呢，谢谢了。

**Comment by CJY0208** [comment]
和 keep-alive 没关系吧，keep-alive 不会操作 css 属性

**Comment by zhaoran12138** [comment]
好的，那我再排查下代码，谢谢了。

**Comment by CJY0208** [comment]
OK，先关了
