### ISSUE TITLE
这是为啥呢

### ISSUE THREAD

**Issue by CJC824** [alitajs/umi-plugin-keep-alive#83]
![lQLPJxbEhmSksDnMxM0CW7AYmijnhUzgKANDDYVoQHAA_603_196](https://user-images.githubusercontent.com/66938629/195024584-508a556c-955f-4b47-9f0d-34188ae2585f.png)

**Comment by CJY0208** [comment]
需要检查是否存在多个 react 或者 react-dom 的版本，如果有的话需要用 packages.json 的 resolutions 来只保留一个版本

可以检查 node_modules 或者 lock 文件
