### ISSUE TITLE
加了KeepAlive切换到新页面再切回缓存页时antd 所有没有icon属性的button 组件会有短暂的loading

### ISSUE THREAD

**Issue by yl196356303** [alitajs/umi-plugin-keep-alive#86]

**Comment by yl196356303** [comment]
这是为什么啊？

**Comment by yl196356303** [comment]
https://user-images.githubusercontent.com/55053022/196354293-656c5a16-e16a-407b-9db1-5bf78776feff.mp4

**Comment by CJY0208** [comment]
这个问题已经记录到了，还没有时间跟进
https://github.com/CJY0208/react-activation/issues/225
