### ISSUE TITLE
动态修改 keepalive 配置 缓存未生效

### ISSUE THREAD

**Issue by Kotoba209** [alitajs/umi-plugin-keep-alive#97]
在配置文件里加上路由可以缓存成功，但是通过 patchKeepAlive 动态添加的确不能，请问这是什么原因呢？

![image](https://github.com/alitajs/umi-plugin-keep-alive/assets/45581808/b0677709-24d8-4984-aeb2-f1ad47e2d6c5)

![image](https://github.com/alitajs/umi-plugin-keep-alive/assets/45581808/595715ee-f10e-4a0e-92de-462191ecb3a5)

![image](https://github.com/alitajs/umi-plugin-keep-alive/assets/45581808/50206b97-af94-4e01-aef4-a756730cc36b)

**Comment by CJY0208** [comment]
好像 issues 提错地方了，应该在 这里提 https://github.com/alitajs/alita
