### ISSUE TITLE
[建议] plugin-keepalive 生成能否加入 umi setup中

### ISSUE THREAD

**Issue by CodeYHJ** [alitajs/umi-plugin-keep-alive#98]
@umi/max

**Comment by CodeYHJ** [comment]
使用@umi/max

版本: umi@4.0.70

场景:

在 CI 过程中, 需要做lint, 但 pnpm install 时候, .umi中不存在 plugin-keepalive文件. plugin-keepalive的生成是在 dev 或者 build 指令时候产生.

当前需增加一个job, 先运行 dev指令 生成 .umi/plugin-keepalive文件后, copy并缓存下来, 然后在执行 lint 指令时候, 再copy进所需要的job.

**Comment by CJY0208** [comment]
你说的插件似乎是 alita 仓库里的 keepalive 而不是这个

**Comment by CodeYHJ** [comment]
> 你说的插件似乎是 alita 仓库里的 keepalive 而不是这个

抱歉, 此issues关闭吧!
